<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;


use App\Models\Product_Images;

class Product_ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function init()
    {
        $data = array(
            array(
                'Name'=>"S01-1.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"S01-2.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"S01-3.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"S02-1.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"S02-2.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"S02-3.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"S03-1.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"S03-2.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"S03-3.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"S04-1.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"S04-2.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"S04-3.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"S05-1.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"S05-2.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"S05-3.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"S06-1.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"S06-2.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"S06-3.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"S07-1.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"S07-2.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"S07-3.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"S08-1.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"S08-2.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"S08-3.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"S09-1.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"S09-2.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"S09-3.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"S10-1.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"S10-2.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"S10-3.JPG",
                'ProductId'=>"10"
            ),
        );
        $data2 = array(
            array(
                'Name'=>"T01-1.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"T01-2.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"T01-3.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"T02-1.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"T02-2.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"T02-3.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"T03-1.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"T03-2.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"T03-3.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"T04-1.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"T04-2.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"T04-3.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"T05-1.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"T05-2.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"T05-3.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"T06-1.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"T06-2.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"T06-3.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"T07-1.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"T07-2.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"T07-3.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"T08-1.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"T08-2.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"T08-3.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"T09-1.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"T09-2.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"T09-3.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"T10-1.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"T10-2.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"T10-3.JPG",
                'ProductId'=>"10"
            ),
        );
        $data3 = array(
            array(
                'Name'=>"M01-1.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"M01-2.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"M01-3.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"M02-1.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"M02-2.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"M02-3.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"M03-1.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"M03-2.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"M03-3.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"M04-1.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"M04-2.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"M04-3.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"M05-1.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"M05-2.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"M05-3.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"M06-1.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"M06-2.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"M06-3.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"M07-1.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"M07-2.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"M07-3.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"M08-1.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"M08-2.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"M08-3.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"M09-1.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"M09-2.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"M09-3.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"M10-1.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"M10-2.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"M10-3.JPG",
                'ProductId'=>"10"
            ),
        );
        $data4 = array(
            array(
                'Name'=>"G01-1.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"G01-2.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"G01-3.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"G02-1.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"G02-2.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"G02-3.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"G03-1.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"G03-2.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"G03-3.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"G04-1.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"G04-2.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"G04-3.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"G05-1.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"G05-2.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"G05-3.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"G06-1.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"G06-2.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"G06-3.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"G07-1.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"G07-2.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"G07-3.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"G08-1.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"G08-2.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"G08-3.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"G09-1.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"G09-2.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"G09-3.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"G10-1.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"G10-2.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"G10-3.JPG",
                'ProductId'=>"10"
            ),
        );
        $data5 = array(
            array(
                'Name'=>"X01-1.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"X01-2.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"X01-3.JPG",
                'ProductId'=>"1"
            ),
            array(
                'Name'=>"X02-1.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"X02-2.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"X02-3.JPG",
                'ProductId'=>"2"
            ),
            array(
                'Name'=>"X03-1.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"X03-2.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"X03-3.JPG",
                'ProductId'=>"3"
            ),
            array(
                'Name'=>"X04-1.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"X04-2.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"X04-3.JPG",
                'ProductId'=>"4"
            ),
            array(
                'Name'=>"X05-1.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"X05-2.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"X05-3.JPG",
                'ProductId'=>"5"
            ),
            array(
                'Name'=>"X06-1.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"X06-2.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"X06-3.JPG",
                'ProductId'=>"6"
            ),
            array(
                'Name'=>"X07-1.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"X07-2.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"X07-3.JPG",
                'ProductId'=>"7"
            ),
            array(
                'Name'=>"X08-1.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"X08-2.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"X08-3.JPG",
                'ProductId'=>"8"
            ),
            array(
                'Name'=>"X09-1.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"X09-2.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"X09-3.JPG",
                'ProductId'=>"9"
            ),
            array(
                'Name'=>"X10-1.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"X10-2.JPG",
                'ProductId'=>"10"
            ),
            array(
                'Name'=>"X10-3.JPG",
                'ProductId'=>"10"
            ),
        );
        //Product_Images::insert($data);
        //Product_Images::insert($data2);
        //Product_Images::insert($data3);
        //Product_Images::insert($data4);
        Product_Images::insert($data5);
        $test =Product_Images::all();
        echo $test;
    }
}
